---
# yamllint configuration for AI code review project

extends: relaxed

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  trailing-spaces: enable
  empty-lines:
    max: 2
